#!/usr/bin/env python3
"""Extract font metrics from a font file into JSON.

The browser's `fontBoundingBox*` / `line-height: normal` values come from the
platform font backend, so they can differ between browsers and operating
systems. Terminal cell metrics have to be exact, so the demo ships the metrics
it needs next to the font and passes them to `Terminal` as `fontMetrics`
(see lib/metrics.ts).

This mirrors what Ghostty reads from the same tables in
`src/font/face/freetype.zig`:

  * vertical metrics: OS/2 sTypo* when USE_TYPO_METRICS is set, else hhea,
    else OS/2 sTypo*, else OS/2 usWin*
  * cell width: the widest advance of the printable ASCII range
  * underline: `post` (with Ghostty's broken-table handling)
  * strikethrough: OS/2 yStrikeout*
  * cap/x height: OS/2 sCapHeight / sxHeight

Usage:
    python3 scripts/build-font-metrics.py demo/fonts/MapleMono-Regular.woff2 \
        --family "Maple Mono" -o demo/fonts/MapleMono-metrics.json

Requires fontTools (`pip install fonttools brotli`).
"""

from __future__ import annotations

import argparse
import json
import sys

try:
    from fontTools.ttLib import TTFont
except ImportError:  # pragma: no cover
    sys.exit("fontTools is required: pip install fonttools brotli")

ASCII_START, ASCII_END = 32, 126


def vertical_metrics(font: TTFont) -> tuple[float, float, float]:
    """Ascent, descent (negative) and line gap, following Ghostty's precedence."""
    hhea = font["hhea"]
    os2 = font.get("OS/2")

    if os2 is not None and os2.fsSelection & (1 << 7):  # USE_TYPO_METRICS
        return float(os2.sTypoAscender), float(os2.sTypoDescender), float(os2.sTypoLineGap)

    if hhea.ascender != 0 or hhea.descender != 0:
        return float(hhea.ascender), float(hhea.descender), float(hhea.lineGap)

    if os2 is not None and (os2.sTypoAscender != 0 or os2.sTypoDescender != 0):
        return float(os2.sTypoAscender), float(os2.sTypoDescender), float(os2.sTypoLineGap)

    if os2 is not None:
        # usWinDescent is positive-down unlike the others
        return float(os2.usWinAscent), float(-os2.usWinDescent), 0.0

    raise SystemExit("font has neither hhea nor OS/2 metrics")


def advance_width(font: TTFont) -> float:
    """Widest advance width in the printable ASCII range."""
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]
    widths = []
    for code in range(ASCII_START, ASCII_END + 1):
        glyph = cmap.get(code)
        if glyph is not None:
            widths.append(hmtx[glyph][0])
    if not widths:
        raise SystemExit("could not measure any ASCII advance widths")
    return float(max(widths))


def underline_metrics(font: TTFont) -> tuple[float | None, float | None]:
    """`post` underline position/thickness, with Ghostty's degenerate handling."""
    post = font.get("post")
    if post is None:
        return None, None

    broken = post.underlineThickness == 0
    position = None
    if not (broken and post.underlinePosition == 0):
        position = float(post.underlinePosition)
    thickness = None if broken else float(post.underlineThickness)
    return position, thickness


def strikethrough_metrics(font: TTFont) -> tuple[float | None, float | None]:
    """OS/2 yStrikeout position/thickness, with Ghostty's degenerate handling."""
    os2 = font.get("OS/2")
    if os2 is None:
        return None, None

    broken = os2.yStrikeoutSize == 0
    position = None
    if not (broken and os2.yStrikeoutPosition == 0):
        position = float(os2.yStrikeoutPosition)
    thickness = None if broken else float(os2.yStrikeoutSize)
    return position, thickness


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("font", help="font file (.woff2, .ttf, .otf)")
    parser.add_argument("--family", help="family name recorded in the output")
    parser.add_argument("-o", "--output", required=True, help="output JSON path")
    args = parser.parse_args()

    font = TTFont(args.font)
    upem = font["head"].unitsPerEm
    ascent, descent, line_gap = vertical_metrics(font)
    underline_position, underline_thickness = underline_metrics(font)
    strike_position, strike_thickness = strikethrough_metrics(font)

    os2 = font.get("OS/2")
    cap_height = float(os2.sCapHeight) if os2 is not None and os2.version >= 2 else None
    ex_height = float(os2.sxHeight) if os2 is not None and os2.version >= 2 else None
    if cap_height is not None and cap_height <= 0:
        cap_height = None
    if ex_height is not None and ex_height <= 0:
        ex_height = None

    metrics = {
        "$comment": (
            "Generated by scripts/build-font-metrics.py. Font metrics in font units, "
            "read from the font tables so cell metrics do not depend on browser or "
            "platform font APIs. See lib/metrics.ts."
        ),
        "family": args.family or font["name"].getDebugName(1),
        "source": args.font.split("/")[-1],
        "unitsPerEm": upem,
        "ascent": ascent,
        "descent": descent,
        "lineGap": line_gap,
        "advanceWidth": advance_width(font),
        "underlinePosition": underline_position,
        "underlineThickness": underline_thickness,
        "strikethroughPosition": strike_position,
        "strikethroughThickness": strike_thickness,
        "capHeight": cap_height,
        "exHeight": ex_height,
    }

    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2)
        f.write("\n")

    print(f"wrote {args.output}")
    for key, value in metrics.items():
        if not key.startswith("$"):
            print(f"  {key:24s} {value}")


if __name__ == "__main__":
    main()
